# action.yml
name: 'aws-cli'
author: Martin Caarels
branding:
  icon: "upload"
  color: green
description: 'Run an aws-cli command'
runs:
  using: 'docker'
  image: 'docker://amazon/aws-cli:latest'
  args:
    - sts
    - get-caller-identity