# action.yml
name: 'aws-cli'
description: 'Run any aws-cli command'
inputs:
  awscommand:  # id of input
    description: 'command to pass to aws-cli'
    required: true
    default: '--version'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - sts get-caller-identity